POST http://localhost:5000/api/countries
Content-Type: application/json

{"code": "FR", "name" : "France", "emoji" : ":fr:"}

###

GET http://localhost:5000/api/countries
Content-Type: application/json

###
